-- V3__fix_duplicate_indexes.sql
-- Fixes duplicate index errors from previous migrations
-- 
-- H2 in-memory databases may have issues with re-applying migrations
-- This file safely removes duplicate indexes if they exist

-- Drop duplicate indexes if they exist (H2 syntax)
DROP INDEX IF EXISTS IDX_STORE_ID;
DROP INDEX IF EXISTS IDX_USER_STORE_ID;
DROP INDEX IF EXISTS IDX_PRODUCT_STORE_ID;
DROP INDEX IF EXISTS IDX_CUSTOMER_STORE_ID;
DROP INDEX IF EXISTS IDX_ORDER_STORE_ID;
DROP INDEX IF EXISTS IDX_INVENTORY_PRODUCT_ID;
DROP INDEX IF EXISTS IDX_INVENTORY_STORE_ID;
DROP INDEX IF EXISTS IDX_STOCK_MOVEMENT_PRODUCT_ID;
DROP INDEX IF EXISTS IDX_STOCK_MOVEMENT_STORE_ID;
DROP INDEX IF EXISTS IDX_DEBT_ORDER_ID;
DROP INDEX IF EXISTS IDX_DEBT_CUSTOMER_ID;
DROP INDEX IF EXISTS IDX_DEBT_STORE_ID;
DROP INDEX IF EXISTS IDX_PAYMENT_DEBT_ID;
DROP INDEX IF EXISTS IDX_PAYMENT_CUSTOMER_ID;
DROP INDEX IF EXISTS IDX_PAYMENT_STORE_ID;
DROP INDEX IF EXISTS IDX_DRAFT_ORDER_CUSTOMER_ID;
DROP INDEX IF EXISTS IDX_DRAFT_ORDER_STORE_ID;
DROP INDEX IF EXISTS IDX_SUBSCRIPTION_CUSTOMER_ID;
DROP INDEX IF EXISTS IDX_SUBSCRIPTION_STORE_ID;
DROP INDEX IF EXISTS IDX_NOTIFICATION_USER_ID;
DROP INDEX IF EXISTS IDX_NOTIFICATION_STORE_ID;
DROP INDEX IF EXISTS IDX_AUDIT_LOG_STORE_ID;
